/* ============================================================
   Page: Store Generator (/store) — Claude-API store generation (mocked)
   ============================================================ */
(function () {
  const { useState } = window.React;
  const L = window.MFLib;
  const h = L.h, Icon = L.Icon;

  // ---- build a real mini storefront HTML from a brand asset ----
  function buildStore(name, desc, brand) {
    const pal = brand ? brand.color_palette : ['#241B14', '#C8794A', '#E8DCC8', '#7A8B6F', '#F6F2EA'];
    const [ink, accent, soft, sage, paper] = pal;
    const font = brand ? brand.font_choices.primary : 'Georgia';
    const tagline = brand ? brand.brand_voice.split('—')[0].trim() : 'Thoughtfully made for everyday ritual';
    const products = [
      ['Signature Espresso Blend', '$24'], ['Gooseneck Pour-Over Kettle', '$79'],
      ['Conical Burr Grinder', '$149'], ['Hand-Thrown Ceramic Cup', '$32'],
      ['Cold Brew Carafe', '$54'], ['Precision Brew Scale', '$39'],
    ];
    const card = (p) => `<div class="p"><div class="ph"></div><div class="pn">${p[0]}</div><div class="pp">${p[1]}</div><button class="add">Add to cart</button></div>`;
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:"${font}",Georgia,serif;color:${ink};background:${paper}}
.nav{display:flex;align-items:center;justify-content:space-between;padding:20px 40px;border-bottom:1px solid ${ink}1a}
.logo{font-size:22px;font-weight:800;letter-spacing:-.02em}
.links{display:flex;gap:28px;font-size:14px;font-family:system-ui,sans-serif}
.links a{color:${ink};text-decoration:none;opacity:.7}
.cart{background:${accent};color:#fff;border:0;padding:9px 18px;border-radius:999px;font-size:13px;font-family:system-ui,sans-serif;font-weight:600}
.hero{padding:80px 40px;text-align:center;background:${soft}}
.hero h1{font-size:52px;line-height:1.05;letter-spacing:-.03em;max-width:14ch;margin:0 auto 18px}
.hero p{font-family:system-ui,sans-serif;font-size:17px;opacity:.65;max-width:46ch;margin:0 auto 28px}
.btn{background:${ink};color:${paper};border:0;padding:14px 30px;border-radius:999px;font-size:15px;font-family:system-ui,sans-serif;font-weight:600;cursor:pointer}
.section{padding:64px 40px}
.section h2{font-size:30px;letter-spacing:-.02em;margin-bottom:28px;text-align:center}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;max-width:1000px;margin:0 auto}
.p{background:#fff;border:1px solid ${ink}14;border-radius:14px;padding:16px;text-align:center}
.ph{height:150px;border-radius:10px;background:repeating-linear-gradient(135deg,${soft},${soft} 12px,${sage}55 12px,${sage}55 24px);margin-bottom:14px}
.pn{font-weight:600;font-size:16px;margin-bottom:4px}
.pp{font-family:system-ui,sans-serif;color:${accent};font-weight:700;margin-bottom:12px}
.add{width:100%;background:${soft};color:${ink};border:0;padding:10px;border-radius:8px;font-family:system-ui,sans-serif;font-size:13px;font-weight:600;cursor:pointer}
.band{background:${sage};color:#fff;text-align:center;padding:56px 40px}
.band h3{font-size:26px;letter-spacing:-.02em;margin-bottom:10px}
.band p{font-family:system-ui,sans-serif;opacity:.85}
.foot{padding:30px 40px;text-align:center;font-family:system-ui,sans-serif;font-size:13px;opacity:.55;border-top:1px solid ${ink}1a}
</style></head><body>
<div class="nav"><div class="logo">${name}</div><div class="links"><a>Shop</a><a>Our Story</a><a>Journal</a></div><button class="cart">Cart · 0</button></div>
<div class="hero"><h1>${tagline}</h1><p>${desc || 'Premium coffee gear, curated for people who love the craft.'}</p><button class="btn">Shop the collection</button></div>
<div class="section"><h2>Best sellers</h2><div class="grid">${products.map(card).join('')}</div></div>
<div class="band"><h3>Free shipping over $50</h3><p>Roasted to order · 30-day returns · Carbon-neutral delivery</p></div>
<div class="foot">© ${new Date().getFullYear()} ${name} · Generated by MarketForge AI</div>
</body></html>`;
  }

  function genFiles(name, desc, brand) {
    const html = buildStore(name, desc, brand);
    return [
      { filename: 'index.html', content: html },
      { filename: 'styles.css', content: '/* Styles are inlined in index.html for this build. */' },
      { filename: 'script.js', content: "document.querySelectorAll('.add,.cart,.btn').forEach(b=>b.addEventListener('click',()=>b.textContent='Added ✓'));" },
    ];
  }

  function StoreGenerator() {
    const store = L.useStore();
    const st = store.get();
    const [name, setName] = useState('');
    const [desc, setDesc] = useState('');
    const [brandId, setBrandId] = useState('');
    const [phase, setPhase] = useState('idle'); // idle | generating | ready | failed
    const [current, setCurrent] = useState(null); // {store_name, files, html}
    const [pending, setPending] = useState(null); // regenerated awaiting accept
    const [nameErr, setNameErr] = useState('');
    const [failNext, setFailNext] = useState(false);

    function run(isRegen) {
      if (!isRegen && !name.trim()) { setNameErr('Store name is required.'); return; }
      const brand = st.brand_assets.find((b) => b.id === brandId);
      const sName = isRegen ? current.store_name : name.trim();
      setPhase('generating');
      const task = store.addTask('Generate Store', { store: sName });
      const gs = isRegen ? null : store.addStore(sName, 'Generating');
      setTimeout(() => {
        if (failNext && !isRegen) {
          setPhase('failed');
          store.finishTask(task.id, 'Failed', { error_message: 'Generated output was missing required files (index.html). Model returned an incomplete response.' });
          if (gs) store.updateStore(gs.id, { status: 'Failed', error_message: 'Incomplete output — missing index.html.' });
          setFailNext(false);
          return;
        }
        const files = genFiles(sName, isRegen ? current.desc : desc, brand);
        const result = { store_name: sName, files, html: files[0].content, desc: isRegen ? current.desc : desc, brand };
        store.finishTask(task.id, 'Completed', { details: { store: sName } });
        if (isRegen) { setPending(result); window.MFToast('info', 'New version ready', 'Review it, then keep or discard.'); }
        else { setCurrent(result); if (gs) store.updateStore(gs.id, { status: 'Ready', generated_files: files }); }
        setPhase('ready');
      }, 3000);
    }

    function download() {
      const blob = new Blob([current.html], { type: 'text/html' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = current.store_name.replace(/\s+/g, '-').toLowerCase() + '.html';
      a.click();
      window.MFToast('success', 'Download started', current.files.length + ' files packaged');
    }

    return h('div', { className: 'content fade-in' },
      h('div', { className: 'page-head' },
        h('h2', null, 'Store Generator'),
        h('p', null, 'Generate a complete, self-contained storefront from your brand and catalog — preview, refine, and download.')),

      h('div', { className: 'grid', style: { gridTemplateColumns: '340px 1fr', alignItems: 'start' } },
        // left: form + history
        h('div', { className: 'grid', style: { gap: 18 } },
          h('div', { className: 'card card-pad', style: { display: 'flex', flexDirection: 'column', gap: 16 } },
            h(L.Field, { label: 'Store name', error: nameErr },
              h('input', { className: 'input' + (nameErr ? ' error' : ''), placeholder: 'e.g. Driftwood Coffee Co.', value: name, onChange: (e) => { setName(e.target.value); setNameErr(''); } })),
            h(L.Field, { label: 'Product / niche description' },
              h('textarea', { className: 'textarea', placeholder: 'Describe what the store sells…', value: desc, onChange: (e) => setDesc(e.target.value) })),
            h(L.Field, { label: 'Apply brand asset', hint: 'Optional — pulls palette, type & voice' },
              h('select', { className: 'select', value: brandId, onChange: (e) => setBrandId(e.target.value) },
                h('option', { value: '' }, 'None — use defaults'),
                st.brand_assets.map((b) => h('option', { key: b.id, value: b.id }, b.brand_name)))),
            h('label', { className: 'flex center gap-8', style: { fontSize: 12.5, color: 'var(--muted)', cursor: 'pointer' } },
              h('input', { type: 'checkbox', checked: failNext, onChange: (e) => setFailNext(e.target.checked) }), 'Simulate a generation failure'),
            h('button', { className: 'btn btn-primary btn-block', disabled: phase === 'generating', onClick: () => run(false) },
              h(Icon, { name: phase === 'generating' ? 'refresh' : 'store', size: 16, className: phase === 'generating' ? 'spin' : '' }), phase === 'generating' ? 'Generating…' : 'Generate store')),

          h('div', { className: 'notice' },
            h('div', { className: 'notice-ico' }, h(Icon, { name: 'store', size: 20 })),
            h('div', null, h('h4', null, 'Shopify integration coming soon'),
              h('p', null, 'Connect your Shopify store to deploy directly in a future release.'))),

          h('div', { className: 'card' },
            h('div', { className: 'card-head' }, h('h3', null, 'Previous stores'), h('span', { className: 'sub', style: { marginLeft: 'auto' } }, st.generated_stores.length)),
            st.generated_stores.length === 0 ? h(L.Empty, { icon: 'store', title: 'No stores yet' }) :
              st.generated_stores.map((g) => h('div', { key: g.id, style: { padding: '13px 18px', borderBottom: '1px solid var(--line)', display: 'flex', alignItems: 'center', gap: 10 } },
                h('div', { style: { flex: 1 } }, h('div', { className: 't-strong', style: { fontSize: 13.5 } }, g.store_name), h('div', { className: 't-muted mono', style: { fontSize: 11.5, marginTop: 3 } }, L.timeAgo(g.created_at))),
                h(L.StatusBadge, { status: g.status }))))),

        // right: preview
        h('div', null,
          phase === 'generating' ? h('div', { className: 'card', style: { minHeight: 480 } }, h('div', { className: 'gen-loader' },
            h('div', { className: 'ring' }), h('h4', null, 'Generating your storefront…'), h('p', null, 'Calling the model and assembling files'),
            h(StoreSteps, null)))
          : phase === 'failed' ? h('div', { className: 'card card-pad', style: { minHeight: 480 } }, h(L.Empty, {
              icon: 'alert', title: 'Generation failed',
              desc: 'The model returned incomplete output — required files were missing. No charges were applied.',
              action: h('button', { className: 'btn btn-primary', onClick: () => { setPhase('idle'); } }, h(Icon, { name: 'refresh', size: 16 }), 'Retry'),
            }))
          : phase === 'ready' && current ? h(StorePreview, { current, pending, onDownload: download, onRegen: () => run(true), onAcceptPending: () => { setCurrent(pending); setPending(null); window.MFToast('success', 'Updated', 'Kept the regenerated store'); }, onDiscardPending: () => setPending(null) })
          : h('div', { className: 'card', style: { minHeight: 480 } }, h('div', { className: 'gen-loader', style: { color: 'var(--muted)' } },
            h('div', { className: 'empty-ico', style: { width: 60, height: 60 } }, h(Icon, { name: 'store', size: 28 })),
            h('h4', { style: { color: 'var(--ink)' } }, 'Store preview'),
            h('p', null, 'Fill in the form and generate to see a live, interactive storefront here.'))))));
  }

  function StoreSteps() {
    const steps = ['Loading brand context', 'Drafting layout & sections', 'Writing HTML / CSS / JS', 'Validating output files'];
    const [done, setDone] = useState(0);
    window.React.useEffect(() => {
      const timers = steps.map((_, i) => setTimeout(() => setDone(i + 1), (i + 1) * 680));
      return () => timers.forEach(clearTimeout);
    }, []);
    return h('div', { className: 'steps' }, steps.map((s, i) => h('div', { key: i, className: 'step' + (i < done ? ' done' : i === done ? ' active' : '') },
      h('div', { className: 'sdot' }, i < done && h(Icon, { name: 'check', size: 11 })), s)));
  }

  function StorePreview({ current, pending, onDownload, onRegen, onAcceptPending, onDiscardPending }) {
    const view = pending || current;
    return h('div', { className: 'card' },
      h('div', { className: 'card-head' },
        h('h3', null, view.store_name),
        h('span', { className: 'badge badge-done', style: { marginLeft: 10 } }, h(Icon, { name: 'check', size: 12 }), pending ? 'New version' : 'Ready'),
        h('div', { className: 'flex center gap-8', style: { marginLeft: 'auto' } },
          h('button', { className: 'btn btn-ghost btn-sm', onClick: onRegen }, h(Icon, { name: 'refresh', size: 14 }), 'Regenerate'),
          h('button', { className: 'btn btn-primary btn-sm', onClick: onDownload }, h(Icon, { name: 'download', size: 14 }), 'Download ZIP'))),

      pending && h('div', { className: 'notice', style: { margin: '16px 22px 0', background: 'var(--violet-soft)', borderColor: 'oklch(0.88 0.05 300)' } },
        h('div', { className: 'notice-ico', style: { color: 'oklch(0.5 0.15 300)' } }, h(Icon, { name: 'sparkle', size: 20 })),
        h('div', { style: { flex: 1 } }, h('h4', { style: { color: 'oklch(0.45 0.15 300)' } }, 'New version ready'),
          h('p', { style: { color: 'var(--ink-2)' } }, 'Previewing the regenerated store. The previous version is kept until you decide.')),
        h('div', { className: 'flex gap-8' },
          h('button', { className: 'btn btn-ghost btn-sm', onClick: onDiscardPending }, 'Discard'),
          h('button', { className: 'btn btn-primary btn-sm', onClick: onAcceptPending }, 'Keep new'))),

      h('div', { className: 'card-pad' },
        h('div', { style: { border: '1px solid var(--line)', borderRadius: 12, overflow: 'hidden' } },
          h('div', { className: 'browser-chrome' },
            h('div', { className: 'browser-dot', style: { background: '#f56' } }),
            h('div', { className: 'browser-dot', style: { background: '#fb5' } }),
            h('div', { className: 'browser-dot', style: { background: '#5c5' } }),
            h('div', { className: 'browser-url' }, view.store_name.replace(/\s+/g, '').toLowerCase() + '.myshop.co')),
          h('iframe', { className: 'preview-frame', srcDoc: view.html, title: 'Store preview' })),
        h('div', { className: 'flex wrap gap-8', style: { marginTop: 14 } },
          view.files.map((f) => h('span', { key: f.filename, className: 'tag', style: { fontFamily: 'var(--mono)' } }, h(Icon, { name: 'seo', size: 12, style: { marginRight: 5 } }), f.filename)))));
  }

  window.MFPages = Object.assign(window.MFPages || {}, { StoreGenerator });
})();
