/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dash': typeof DashRoute
}
export interface FileRoutesByTo {
  '/dash': typeof DashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dash': typeof DashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dash'
  fileRoutesByTo: FileRoutesByTo
  to: '/dash'
  id: '__root__' | '/dash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
