/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppStoreRouteImport } from './routes/_authenticated/app.store'
import { Route as AuthenticatedAppSeoRouteImport } from './routes/_authenticated/app.seo'
import { Route as AuthenticatedAppDiscoveryRouteImport } from './routes/_authenticated/app.discovery'
import { Route as AuthenticatedAppCompetitorsRouteImport } from './routes/_authenticated/app.competitors'
import { Route as AuthenticatedAppBrandRouteImport } from './routes/_authenticated/app.brand'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as ApiPublicHooksDbBackupRouteImport } from './routes/api/public/hooks/db-backup'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStoreRoute = AuthenticatedAppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSeoRoute = AuthenticatedAppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoveryRoute =
  AuthenticatedAppDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompetitorsRoute =
  AuthenticatedAppCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrandRoute = AuthenticatedAppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksDbBackupRoute = ApiPublicHooksDbBackupRouteImport.update({
  id: '/api/public/hooks/db-backup',
  path: '/api/public/hooks/db-backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dash': typeof DashRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/discovery': typeof AuthenticatedAppDiscoveryRoute
  '/app/seo': typeof AuthenticatedAppSeoRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dash': typeof DashRoute
  '/s/$slug': typeof SSlugRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/brand': typeof AuthenticatedAppBrandRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/discovery': typeof AuthenticatedAppDiscoveryRoute
  '/app/seo': typeof AuthenticatedAppSeoRoute
  '/app/store': typeof AuthenticatedAppStoreRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dash': typeof DashRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/brand': typeof AuthenticatedAppBrandRoute
  '/_authenticated/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/_authenticated/app/discovery': typeof AuthenticatedAppDiscoveryRoute
  '/_authenticated/app/seo': typeof AuthenticatedAppSeoRoute
  '/_authenticated/app/store': typeof AuthenticatedAppStoreRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/db-backup': typeof ApiPublicHooksDbBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dash'
    | '/app'
    | '/s/$slug'
    | '/app/alerts'
    | '/app/brand'
    | '/app/competitors'
    | '/app/discovery'
    | '/app/seo'
    | '/app/store'
    | '/app/tasks'
    | '/app/'
    | '/api/public/hooks/db-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dash'
    | '/s/$slug'
    | '/app/alerts'
    | '/app/brand'
    | '/app/competitors'
    | '/app/discovery'
    | '/app/seo'
    | '/app/store'
    | '/app/tasks'
    | '/app'
    | '/api/public/hooks/db-backup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dash'
    | '/_authenticated/app'
    | '/s/$slug'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/brand'
    | '/_authenticated/app/competitors'
    | '/_authenticated/app/discovery'
    | '/_authenticated/app/seo'
    | '/_authenticated/app/store'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/'
    | '/api/public/hooks/db-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashRoute: typeof DashRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicHooksDbBackupRoute: typeof ApiPublicHooksDbBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/store': {
      id: '/_authenticated/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AuthenticatedAppStoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo': {
      id: '/_authenticated/app/seo'
      path: '/seo'
      fullPath: '/app/seo'
      preLoaderRoute: typeof AuthenticatedAppSeoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/discovery': {
      id: '/_authenticated/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AuthenticatedAppDiscoveryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/competitors': {
      id: '/_authenticated/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AuthenticatedAppCompetitorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brand': {
      id: '/_authenticated/app/brand'
      path: '/brand'
      fullPath: '/app/brand'
      preLoaderRoute: typeof AuthenticatedAppBrandRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/db-backup': {
      id: '/api/public/hooks/db-backup'
      path: '/api/public/hooks/db-backup'
      fullPath: '/api/public/hooks/db-backup'
      preLoaderRoute: typeof ApiPublicHooksDbBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppBrandRoute: typeof AuthenticatedAppBrandRoute
  AuthenticatedAppCompetitorsRoute: typeof AuthenticatedAppCompetitorsRoute
  AuthenticatedAppDiscoveryRoute: typeof AuthenticatedAppDiscoveryRoute
  AuthenticatedAppSeoRoute: typeof AuthenticatedAppSeoRoute
  AuthenticatedAppStoreRoute: typeof AuthenticatedAppStoreRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppBrandRoute: AuthenticatedAppBrandRoute,
  AuthenticatedAppCompetitorsRoute: AuthenticatedAppCompetitorsRoute,
  AuthenticatedAppDiscoveryRoute: AuthenticatedAppDiscoveryRoute,
  AuthenticatedAppSeoRoute: AuthenticatedAppSeoRoute,
  AuthenticatedAppStoreRoute: AuthenticatedAppStoreRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashRoute: DashRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicHooksDbBackupRoute: ApiPublicHooksDbBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
